services:
  broker-mosquitto:
    image: eclipse-mosquitto:2.0-openssl
    container_name: broker-mosquitto
    ports:
      - '1883:1883'
    volumes:
      - '${PWD}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf'
