#!/bin/bash

PROTO_FILES=$(find common/model/schema/proto3 -iname "*.proto")

mkdir -p common/model/gen

protoc --proto_path=common/model/schema/proto3 --python_out=common/model/gen --pyi_out=common/model/gen $PROTO_FILES
