name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  get_it: ^7.6.7
  intl: ^0.19.0
  latlong2: ^0.9.1
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.1.2
  sensors_plus: ^4.0.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^25.1.35
  talker_flutter: ^4.0.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
