// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: monitoring/monitoring.proto

package monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	proto "points-consumer/lib/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccoundId string `protobuf:"bytes,1,opt,name=accound_id,json=accoundId,proto3" json:"accound_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserAccount) Reset() {
	*x = UserAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monitoring_monitoring_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccount) ProtoMessage() {}

func (x *UserAccount) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_monitoring_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccount.ProtoReflect.Descriptor instead.
func (*UserAccount) Descriptor() ([]byte, []int) {
	return file_monitoring_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *UserAccount) GetAccoundId() string {
	if x != nil {
		return x.AccoundId
	}
	return ""
}

func (x *UserAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AccelerometerRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *proto.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	X    float32          `protobuf:"fixed32,11,opt,name=x,proto3" json:"x,omitempty"`
	Y    float32          `protobuf:"fixed32,12,opt,name=y,proto3" json:"y,omitempty"`
	Z    float32          `protobuf:"fixed32,13,opt,name=z,proto3" json:"z,omitempty"`
	Ms   int32            `protobuf:"varint,21,opt,name=ms,proto3" json:"ms,omitempty"`
}

func (x *AccelerometerRecord) Reset() {
	*x = AccelerometerRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monitoring_monitoring_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccelerometerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccelerometerRecord) ProtoMessage() {}

func (x *AccelerometerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_monitoring_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccelerometerRecord.ProtoReflect.Descriptor instead.
func (*AccelerometerRecord) Descriptor() ([]byte, []int) {
	return file_monitoring_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *AccelerometerRecord) GetTime() *proto.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *AccelerometerRecord) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AccelerometerRecord) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AccelerometerRecord) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *AccelerometerRecord) GetMs() int32 {
	if x != nil {
		return x.Ms
	}
	return 0
}

type GyroscopeRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *proto.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	X    float32          `protobuf:"fixed32,11,opt,name=x,proto3" json:"x,omitempty"`
	Y    float32          `protobuf:"fixed32,12,opt,name=y,proto3" json:"y,omitempty"`
	Z    float32          `protobuf:"fixed32,13,opt,name=z,proto3" json:"z,omitempty"`
	Ms   int32            `protobuf:"varint,21,opt,name=ms,proto3" json:"ms,omitempty"`
}

func (x *GyroscopeRecord) Reset() {
	*x = GyroscopeRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monitoring_monitoring_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GyroscopeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GyroscopeRecord) ProtoMessage() {}

func (x *GyroscopeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_monitoring_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GyroscopeRecord.ProtoReflect.Descriptor instead.
func (*GyroscopeRecord) Descriptor() ([]byte, []int) {
	return file_monitoring_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *GyroscopeRecord) GetTime() *proto.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GyroscopeRecord) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GyroscopeRecord) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GyroscopeRecord) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *GyroscopeRecord) GetMs() int32 {
	if x != nil {
		return x.Ms
	}
	return 0
}

type GpsRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      *proto.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Latitude  float64          `protobuf:"fixed64,11,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64          `protobuf:"fixed64,12,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy  float64          `protobuf:"fixed64,13,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Ms        int32            `protobuf:"varint,21,opt,name=ms,proto3" json:"ms,omitempty"`
}

func (x *GpsRecord) Reset() {
	*x = GpsRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monitoring_monitoring_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GpsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsRecord) ProtoMessage() {}

func (x *GpsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_monitoring_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsRecord.ProtoReflect.Descriptor instead.
func (*GpsRecord) Descriptor() ([]byte, []int) {
	return file_monitoring_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *GpsRecord) GetTime() *proto.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GpsRecord) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GpsRecord) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GpsRecord) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *GpsRecord) GetMs() int32 {
	if x != nil {
		return x.Ms
	}
	return 0
}

type Monitoring struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccelerometerRecords []*AccelerometerRecord `protobuf:"bytes,1,rep,name=accelerometer_records,json=accelerometerRecords,proto3" json:"accelerometer_records,omitempty"`
	GyroscopeRecords     []*GyroscopeRecord     `protobuf:"bytes,2,rep,name=gyroscope_records,json=gyroscopeRecords,proto3" json:"gyroscope_records,omitempty"`
	GpsRecords           []*GpsRecord           `protobuf:"bytes,3,rep,name=gps_records,json=gpsRecords,proto3" json:"gps_records,omitempty"`
	Account              *UserAccount           `protobuf:"bytes,11,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *Monitoring) Reset() {
	*x = Monitoring{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monitoring_monitoring_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monitoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitoring) ProtoMessage() {}

func (x *Monitoring) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_monitoring_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitoring.ProtoReflect.Descriptor instead.
func (*Monitoring) Descriptor() ([]byte, []int) {
	return file_monitoring_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *Monitoring) GetAccelerometerRecords() []*AccelerometerRecord {
	if x != nil {
		return x.AccelerometerRecords
	}
	return nil
}

func (x *Monitoring) GetGyroscopeRecords() []*GyroscopeRecord {
	if x != nil {
		return x.GyroscopeRecords
	}
	return nil
}

func (x *Monitoring) GetGpsRecords() []*GpsRecord {
	if x != nil {
		return x.GpsRecords
	}
	return nil
}

func (x *Monitoring) GetAccount() *UserAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_monitoring_monitoring_proto protoreflect.FileDescriptor

var file_monitoring_monitoring_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0a, 0x75, 0x74, 0x69, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x65, 0x6c,
	0x65, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1e,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x73, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6d, 0x73, 0x22, 0x6b, 0x0a, 0x0f, 0x47, 0x79, 0x72, 0x6f,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x73, 0x18, 0x15, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x6d, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x47, 0x70, 0x73, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x73, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6d, 0x73, 0x22, 0x97, 0x02, 0x0a, 0x0a, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x54, 0x0a, 0x15, 0x61, 0x63, 0x63, 0x65,
	0x6c, 0x65, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x6f, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x14, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x65,
	0x72, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x48,
	0x0a, 0x11, 0x67, 0x79, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x79, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x10, 0x67, 0x79, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x0b, 0x67, 0x70, 0x73, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x70, 0x73, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x67, 0x70, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x31, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_monitoring_monitoring_proto_rawDescOnce sync.Once
	file_monitoring_monitoring_proto_rawDescData = file_monitoring_monitoring_proto_rawDesc
)

func file_monitoring_monitoring_proto_rawDescGZIP() []byte {
	file_monitoring_monitoring_proto_rawDescOnce.Do(func() {
		file_monitoring_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(file_monitoring_monitoring_proto_rawDescData)
	})
	return file_monitoring_monitoring_proto_rawDescData
}

var file_monitoring_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_monitoring_monitoring_proto_goTypes = []interface{}{
	(*UserAccount)(nil),         // 0: monitoring.UserAccount
	(*AccelerometerRecord)(nil), // 1: monitoring.AccelerometerRecord
	(*GyroscopeRecord)(nil),     // 2: monitoring.GyroscopeRecord
	(*GpsRecord)(nil),           // 3: monitoring.GpsRecord
	(*Monitoring)(nil),          // 4: monitoring.Monitoring
	(*proto.Timestamp)(nil),     // 5: Timestamp
}
var file_monitoring_monitoring_proto_depIdxs = []int32{
	5, // 0: monitoring.AccelerometerRecord.time:type_name -> Timestamp
	5, // 1: monitoring.GyroscopeRecord.time:type_name -> Timestamp
	5, // 2: monitoring.GpsRecord.time:type_name -> Timestamp
	1, // 3: monitoring.Monitoring.accelerometer_records:type_name -> monitoring.AccelerometerRecord
	2, // 4: monitoring.Monitoring.gyroscope_records:type_name -> monitoring.GyroscopeRecord
	3, // 5: monitoring.Monitoring.gps_records:type_name -> monitoring.GpsRecord
	0, // 6: monitoring.Monitoring.account:type_name -> monitoring.UserAccount
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_monitoring_monitoring_proto_init() }
func file_monitoring_monitoring_proto_init() {
	if File_monitoring_monitoring_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_monitoring_monitoring_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monitoring_monitoring_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccelerometerRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monitoring_monitoring_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GyroscopeRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monitoring_monitoring_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GpsRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monitoring_monitoring_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monitoring); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_monitoring_monitoring_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monitoring_monitoring_proto_goTypes,
		DependencyIndexes: file_monitoring_monitoring_proto_depIdxs,
		MessageInfos:      file_monitoring_monitoring_proto_msgTypes,
	}.Build()
	File_monitoring_monitoring_proto = out.File
	file_monitoring_monitoring_proto_rawDesc = nil
	file_monitoring_monitoring_proto_goTypes = nil
	file_monitoring_monitoring_proto_depIdxs = nil
}
