#!/bin/bash

PROTO_PATH=proto/
PROTO_FILES=$(find $PROTO_PATH -iname "*.proto")
OUTPUT_DIR=dart/generated/proto/

mkdir -p $OUTPUT_DIR

protoc --proto_path=$PROTO_PATH --dart_out=$OUTPUT_DIR $PROTO_FILES
