#!/bin/bash

PROTO_FILES=$(find src/common/model/schema/proto3 -iname "*.proto")

mkdir -p src/common/model/gen

protoc --proto_path=src/common/model/schema/proto3 --python_out=src/common/model/gen --pyi_out=src/common/model/gen $PROTO_FILES
