name: Build apks

on: workflow_dispatch

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - run: flutter pub get
        working-directory: mobile

      - name: Build apk
        working-directory: mobile
        run: |-
          flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: ./mobile/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
          compression-level: 0
